site:
  title: TTS Tools (Community Fork)
  url: https://eunomiac.github.io/tts-tools
  start_page: editor::index.adoc
content:
  sources:
    - url: ..
      start_paths:
        - packages/*/docs
      branches: HEAD
      edit_url: https://github.com/Eunomiac/tts-tools/edit/main/{path}
urls:
  latest_version_segment: latest
  latest_prerelease_version_segment: next
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./ui
antora:
  extensions:
    - require: "@antora/lunr-extension"
      index_latest_only: true
      snippet_length: 200
asciidoc:
  attributes:
    experimental: true
